export function createAppViewProps({
  appData,
  dashboardAppData,
  insightsAppData,
  supabaseCreditCards,
  supabaseMonthlyBalances,
  selectedBalanceMonth,
  creditCardsLoading,
  creditCardsError,
  creditCardsSaving,
  monthlyBalancesLoading,
  monthlyBalancesSaving,
  monthlyBalancesError,
  householdProfiles,
  householdProfilesLoading,
  householdProfilesSaving,
  householdProfilesError,
  supabaseBudgets,
  selectedBudgetMonth,
  budgetsLoading,
  budgetsError,
  budgetsSaving,
  spendingCategories,
  spendingTransactions,
  selectedSpendingMonth,
  spendingLoading,
  spendingError,
  spendingSaving,
  spendingCategoriesLoading,
  spendingCategoriesError,
  recurringCategories,
  recurringPayments,
  recurringStatusByMonth,
  recurringTransactions,
  selectedRecurringMonth,
  recurringLoading,
  recurringError,
  recurringSaving,
  recurringCategoriesLoading,
  recurringCategoriesError,
  selectedDashboardMonth,
  dashboardLoading,
  dashboardError,
  monthlyCloseReview,
  monthlyCloseReviewLoading,
  monthlyCloseReviewSaving,
  monthlyCloseReviewError,
  selectedInsightsMonth,
  selectedAccountsMonth,
  selectedLiabilitiesMonth,
  selectedNetWorthMonth,
  selectedIncomeMonth,
  selectedSavingsMonth,
  insightsLoading,
  insightsError,
  incomeSources,
  incomeEntries,
  cashAccounts,
  accountBalanceSnapshots,
  liabilityAccounts,
  liabilityBalanceSnapshots,
  accountsLoading,
  accountsError,
  accountsSaving,
  liabilitiesLoading,
  liabilitiesError,
  liabilitiesSaving,
  incomeLoading,
  incomeError,
  incomeSaving,
  savingsGoals,
  savingsContributions,
  savingsLoading,
  savingsError,
  savingsSaving,
  setSelectedDashboardMonth,
  setSelectedBalanceMonth,
  setSelectedBudgetMonth,
  setSelectedSpendingMonth,
  setSelectedRecurringMonth,
  setSelectedInsightsMonth,
  setSelectedAccountsMonth,
  setSelectedLiabilitiesMonth,
  setSelectedNetWorthMonth,
  setSelectedIncomeMonth,
  setSelectedSavingsMonth,
  toggleMonthlyCloseManualCheck,
  markMonthlyCloseReviewed,
  reopenMonthlyCloseReview,
  createSupabaseCreditCard,
  updateSupabaseCreditCard,
  deleteSupabaseCreditCard,
  saveSupabaseMonthlyBalance,
  refreshData,
  createSupabaseBudget,
  updateSupabaseBudget,
  deleteSupabaseBudget,
  addDefaultBudgetsToSupabase,
  copyPreviousMonthBudgetsToSupabase,
  importLocalBudgetsToSupabase,
  createSupabaseTransaction,
  updateSupabaseTransaction,
  deleteSupabaseTransaction,
  importLocalSpendingToSupabase,
  createSupabaseRecurringPayment,
  updateSupabaseRecurringPayment,
  deleteSupabaseRecurringPayment,
  markSupabaseRecurringPaid,
  markSupabaseRecurringUnpaid,
  skipSupabaseRecurringPayment,
  importLocalRecurringToSupabase,
  refreshSupabaseDataAfterImport,
  createHouseholdProfile,
  saveHouseholdProfile,
  deactivateProfile,
  addDefaultProfiles,
  createSupabaseIncomeSource,
  updateSupabaseIncomeSource,
  deleteSupabaseIncomeSource,
  createSupabaseIncomeEntry,
  updateSupabaseIncomeEntry,
  deleteSupabaseIncomeEntry,
  createSupabaseCashAccount,
  updateSupabaseCashAccount,
  deleteSupabaseCashAccount,
  createSupabaseAccountBalanceSnapshot,
  updateSupabaseAccountBalanceSnapshot,
  deleteSupabaseAccountBalanceSnapshot,
  createSupabaseLiabilityAccount,
  updateSupabaseLiabilityAccount,
  deleteSupabaseLiabilityAccount,
  createSupabaseLiabilityBalanceSnapshot,
  updateSupabaseLiabilityBalanceSnapshot,
  deleteSupabaseLiabilityBalanceSnapshot,
  createSupabaseSavingsGoal,
  updateSupabaseSavingsGoal,
  deleteSupabaseSavingsGoal,
  createSupabaseSavingsContribution,
  updateSupabaseSavingsContribution,
  deleteSupabaseSavingsContribution,
} = {}) {
  return {
    dashboardProps: {
      appData: dashboardAppData,
      selectedMonth: selectedDashboardMonth,
      onMonthChange: setSelectedDashboardMonth,
      loading: dashboardLoading,
      error: dashboardError,
      monthlyCloseReview,
      monthlyCloseReviewLoading,
      monthlyCloseReviewSaving,
      monthlyCloseReviewError,
      onToggleMonthlyCloseManualCheck: toggleMonthlyCloseManualCheck,
      onMarkMonthlyCloseReviewed: markMonthlyCloseReviewed,
      onReopenMonthlyCloseReview: reopenMonthlyCloseReview,
    },
    creditCardProps: {
      creditCards: supabaseCreditCards,
      monthlyBalances: supabaseMonthlyBalances,
      selectedBalanceMonth,
      loading: creditCardsLoading,
      error: creditCardsError,
      isSaving: creditCardsSaving,
      monthlyBalancesLoading,
      monthlyBalancesSaving,
      monthlyBalancesError,
      householdProfiles,
      householdProfilesLoading,
      onCreateCard: createSupabaseCreditCard,
      onUpdateCard: updateSupabaseCreditCard,
      onDeleteCard: deleteSupabaseCreditCard,
      onBalanceMonthChange: setSelectedBalanceMonth,
      onMonthlyBalanceChange: saveSupabaseMonthlyBalance,
      onDataChange: refreshData,
    },
    budgetProps: {
      budgets: supabaseBudgets,
      localBudgetsByMonth: appData?.budgetsByMonth,
      selectedMonth: selectedBudgetMonth,
      loading: budgetsLoading,
      error: budgetsError,
      isSaving: budgetsSaving,
      onMonthChange: setSelectedBudgetMonth,
      onCreateBudget: createSupabaseBudget,
      onUpdateBudget: updateSupabaseBudget,
      onDeleteBudget: deleteSupabaseBudget,
      onAddDefaultBudgets: addDefaultBudgetsToSupabase,
      onCopyPreviousMonthBudgets: copyPreviousMonthBudgetsToSupabase,
      onImportLocalBudgets: importLocalBudgetsToSupabase,
    },
    spendingProps: {
      creditCards: supabaseCreditCards,
      categories: spendingCategories,
      transactions: spendingTransactions,
      localTransactions: appData?.transactions,
      selectedMonth: selectedSpendingMonth,
      loading: spendingLoading,
      error: spendingError,
      isSaving: spendingSaving,
      categoriesLoading: spendingCategoriesLoading,
      categoriesError: spendingCategoriesError,
      onMonthChange: setSelectedSpendingMonth,
      onCreateTransaction: createSupabaseTransaction,
      onUpdateTransaction: updateSupabaseTransaction,
      onDeleteTransaction: deleteSupabaseTransaction,
      onImportLocalTransactions: importLocalSpendingToSupabase,
    },
    recurringProps: {
      creditCards: supabaseCreditCards,
      categories: recurringCategories,
      recurringPayments,
      recurringStatusByMonth,
      transactions: recurringTransactions,
      localRecurringPayments: appData?.recurringPayments,
      selectedMonth: selectedRecurringMonth,
      loading: recurringLoading,
      error: recurringError,
      isSaving: recurringSaving,
      categoriesLoading: recurringCategoriesLoading,
      categoriesError: recurringCategoriesError,
      onMonthChange: setSelectedRecurringMonth,
      onCreateRecurringPayment: createSupabaseRecurringPayment,
      onUpdateRecurringPayment: updateSupabaseRecurringPayment,
      onDeleteRecurringPayment: deleteSupabaseRecurringPayment,
      onMarkRecurringPaid: markSupabaseRecurringPaid,
      onMarkRecurringUnpaid: markSupabaseRecurringUnpaid,
      onSkipRecurringPayment: skipSupabaseRecurringPayment,
      onImportLocalRecurringPayments: importLocalRecurringToSupabase,
    },
    insightsProps: {
      appData: insightsAppData,
      selectedMonth: selectedInsightsMonth,
      onMonthChange: setSelectedInsightsMonth,
      loading: insightsLoading,
      error: insightsError,
    },
    accountsProps: {
      cashAccounts,
      accountBalanceSnapshots,
      householdProfiles,
      selectedMonth: selectedAccountsMonth,
      loading: accountsLoading,
      error: accountsError,
      isSaving: accountsSaving,
      onMonthChange: setSelectedAccountsMonth,
      onCreateCashAccount: createSupabaseCashAccount,
      onUpdateCashAccount: updateSupabaseCashAccount,
      onDeleteCashAccount: deleteSupabaseCashAccount,
      onCreateAccountBalanceSnapshot: createSupabaseAccountBalanceSnapshot,
      onUpdateAccountBalanceSnapshot: updateSupabaseAccountBalanceSnapshot,
      onDeleteAccountBalanceSnapshot: deleteSupabaseAccountBalanceSnapshot,
    },
    liabilitiesProps: {
      liabilityAccounts,
      liabilityBalanceSnapshots,
      creditCards: supabaseCreditCards,
      householdProfiles,
      selectedMonth: selectedLiabilitiesMonth,
      loading: liabilitiesLoading,
      error: liabilitiesError,
      isSaving: liabilitiesSaving,
      onMonthChange: setSelectedLiabilitiesMonth,
      onCreateLiabilityAccount: createSupabaseLiabilityAccount,
      onUpdateLiabilityAccount: updateSupabaseLiabilityAccount,
      onDeleteLiabilityAccount: deleteSupabaseLiabilityAccount,
      onCreateLiabilityBalanceSnapshot: createSupabaseLiabilityBalanceSnapshot,
      onUpdateLiabilityBalanceSnapshot: updateSupabaseLiabilityBalanceSnapshot,
      onDeleteLiabilityBalanceSnapshot: deleteSupabaseLiabilityBalanceSnapshot,
    },
    netWorthProps: {
      cashAccounts,
      accountBalanceSnapshots,
      liabilityAccounts,
      liabilityBalanceSnapshots,
      selectedMonth: selectedNetWorthMonth,
      loading: accountsLoading || liabilitiesLoading,
      error: accountsError || liabilitiesError,
      onMonthChange: setSelectedNetWorthMonth,
    },
    incomeProps: {
      incomeSources,
      incomeEntries,
      householdProfiles,
      selectedMonth: selectedIncomeMonth,
      loading: incomeLoading,
      error: incomeError,
      isSaving: incomeSaving,
      onMonthChange: setSelectedIncomeMonth,
      onCreateIncomeSource: createSupabaseIncomeSource,
      onUpdateIncomeSource: updateSupabaseIncomeSource,
      onDeleteIncomeSource: deleteSupabaseIncomeSource,
      onCreateIncomeEntry: createSupabaseIncomeEntry,
      onUpdateIncomeEntry: updateSupabaseIncomeEntry,
      onDeleteIncomeEntry: deleteSupabaseIncomeEntry,
    },
    savingsProps: {
      savingsGoals,
      savingsContributions,
      householdProfiles,
      selectedMonth: selectedSavingsMonth,
      loading: savingsLoading,
      error: savingsError,
      isSaving: savingsSaving,
      onMonthChange: setSelectedSavingsMonth,
      onCreateSavingsGoal: createSupabaseSavingsGoal,
      onUpdateSavingsGoal: updateSupabaseSavingsGoal,
      onDeleteSavingsGoal: deleteSupabaseSavingsGoal,
      onCreateSavingsContribution: createSupabaseSavingsContribution,
      onUpdateSavingsContribution: updateSupabaseSavingsContribution,
      onDeleteSavingsContribution: deleteSupabaseSavingsContribution,
    },
    backupProps: {
      onDataChange: refreshData,
      onSupabaseImportComplete: refreshSupabaseDataAfterImport,
    },
    householdSettingsProps: {
      householdProfiles,
      householdProfilesLoading,
      householdProfilesSaving,
      householdProfilesError,
      onCreateProfile: createHouseholdProfile,
      onUpdateProfile: saveHouseholdProfile,
      onDeactivateProfile: deactivateProfile,
      onCreateDefaultProfiles: addDefaultProfiles,
    },
  };
}
